/* eslint-disable prettier/prettier */
import { backarrow_grey, cycling_icon, dana, dana_jaber, down_arrow, fatmah, forwardarrow_grey, hub1, hub2, hub3, hub4, hub5, jumanah, kholoud, popcorn_dummy, run_icon, swimming_icon, walk_icon, yasmeen } from '../assets';

export const hubData = [{ id: 0, image: hub1, title: 'A Guide to Eating a Balanced Diet', coachName: 'Dietitian Joanne', time: '15 Min' }, { id: 1, image: hub2, title: 'Healthy and Easy Breakfast Recipes', coachName: 'DietHub', time: '1 Hour' }, { id: 2, image: hub3, title: 'Creative Salad Ideas', coachName: 'DietHub', time: '1 Day' }, { id: 3, image: hub4, title: 'Baked Eggs with Spinach and Tomato', coachName: 'Dietitian Joanne', time: '15 Min' }, { id: 4, image: hub5, title: 'How to Choose the Right Carbs', coachName: 'DietiHub', time: '15 Min' }];

export const dates = [{ id: 0, image: backarrow_grey, title: "Yesterday" }, { id: 1, title: "Today", count: "Day 1" }, { id: 2, image: forwardarrow_grey, title: "Tommorow", count: "Day 2" }, { id: 3, image: forwardarrow_grey, title: "Tommorow", count: "Day 3" }, { id: 4, image: forwardarrow_grey, title: "Tommorow", count: "Day 4" }, { id: 5, image: forwardarrow_grey, title: "Tommorow", count: "Day 5" }, { id: 6, image: forwardarrow_grey, title: "Tommorow", count: "Day 6" }, { id: 7, image: forwardarrow_grey, title: "Tommorow", count: "Day 7" }, { id: 8, image: forwardarrow_grey, title: "Tommorow", count: "Day 8" }, { id: 9, image: forwardarrow_grey, title: "Tommorow", count: "Day 9" }, { id: 10, image: forwardarrow_grey, title: "Tommorow", count: "Day 10" }, { id: 11, image: forwardarrow_grey, title: "Tommorow", count: "Day 11" }, { id: 12, image: forwardarrow_grey, title: "Tommorow", count: "Day 12" }, { id: 13, image: forwardarrow_grey, title: "Tommorow", count: "Day 13" }, { id: 14, image: forwardarrow_grey, title: "Tommorow", count: "Day 14" }, { id: 15, image: forwardarrow_grey, title: "Tommorow", count: "Day 15" }]

export const dashData = [{ id: 0, image: popcorn_dummy, item_number: 2, title: "Piece of chicken", desc: "Grilled with no skin" }, { id: 1, image: popcorn_dummy, item_number: 3, title: "Mexi-Egg Wrap", desc: "Scramble one egg and one egg white with beans" }, { id: 2, image: popcorn_dummy, item_number: 1, title: "Tomato baked eggs", desc: "Eggs over tomato for a change" }, { id: 3, image: popcorn_dummy, item_number: 2, title: "Banana bread", desc: "Healthy banana loaf - perfect for breakfast" }, { id: 4, image: popcorn_dummy, item_number: 2, title: "Low-sugar marmalade", desc: "A healthy version of the classic breakfast" }, { id: 5, image: popcorn_dummy, item_number: 1, title: "Melon & crunchy bran pots", desc: "Not just for breakfast, this healthy pot of yoghurt" }];

export const dashDateWise = [{ id: 0, name: "Day 1" }, { id: 1, name: "Day 2" }, { id: 2, name: "Day 3" }, { id: 3, name: "Day 4" }, { id: 4, name: "Day 5" }, { id: 5, name: "Day 6" }, { id: 6, name: "Day 7" }, { id: 7, name: "Day 8" }, { id: 8, name: "Day 9" }, { id: 9, name: "Day 10" }, { id: 10, name: "Day 11" }, { id: 11, name: "Day 12" }, { id: 12, name: "Day 13" }, { id: 13, name: "Day 14" }, { id: 14, name: "Day 15" }]

export const dietData = [{ id: 0, title: 'Snack', image: down_arrow }, { id: 1, title: 'Lunch', image: down_arrow }, { id: 2, title: 'Snack', image: down_arrow }, { id: 3, title: 'Dinner', image: down_arrow }];

export const cupData = [{ id: 0, number: 1, completed: true }, { id: 1, number: 2, completed: true }, { id: 2, number: 3, completed: true }, { id: 3, number: 4, completed: false }, { id: 4, number: 5, completed: false }, { id: 5, number: 6, completed: 'not started' }, { id: 6, number: 7, completed: 'not started' }];

export const ExcerciseData = [{ id: 0, image: walk_icon, time: 30, title: 'Walk', completed: true }, { id: 1, image: run_icon, title: 'Run', time: 20, completed: false }, { id: 2, image: cycling_icon, title: 'Bike', time: 45, completed: false }, { id: 3, image: swimming_icon, title: 'Other', time: 15, completed: 'not started' }]

export const allowedFoods = [{ id: 0, name: 'Fruits' }, { id: 1, name: 'Chicken Breasts' }, { id: 2, name: 'Chia Seeds' }, { id: 3, name: 'Nuts' }, { id: 4, name: 'Chia Seeds' }, { id: 5, name: 'Chicken Breasts' }]

export const restrictedFoods = [{ id: 0, name: 'Fruits' }, { id: 1, name: 'Chicken Breasts' }, { id: 2, name: 'Chia Seeds' }, { id: 3, name: 'Nuts' }, { id: 4, name: 'Chia Seeds' }, { id: 5, name: 'Chicken Breasts' }]

export const coachData = [{ id: 0, image: dana_jaber, name: 'Dana Jaber', designation: 'Nutrition Specialist', rating: 4 }, { id: 1, image: jumanah, name: 'Jumanah Abdulqader', designation: 'Nutrition Specialist', rating: 4 }, { id: 2, image: fatmah, name: 'Fatmah Mohammed', designation: 'Nutrition Specialist', rating: 4 }, { id: 3, image: dana, name: 'Dana Jaber', designation: 'Nutrition Specialist', rating: 4 }, { id: 4, image: yasmeen, name: 'Yasmeen Khalid', designation: 'Nutrition Specialist', rating: 4 }, { id: 5, image: jumanah, name: 'Dana Jaber', designation: 'Nutrition Specialist', rating: 4 }, { id: 6, image: kholoud, name: 'Kholoud Nasser', designation: 'Nutrition Specialist', rating: 4 }, { id: 7, image: dana_jaber, name: 'Dana Jaber', designation: 'Nutrition Specialist', rating: 4 }]

